# Generated by Django 3.1.5 on 2021-01-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertasksapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertasksapi.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertasksapi.user')),
            ],
        ),
    ]
