# Generated by Django 3.1.5 on 2021-01-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertasksapi', '0002_task_usertask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='task',
            name='code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='Descrição',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Estado',
            field=models.CharField(default='pendente', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usertasksapi.user'),
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
