# Generated by Django 3.1.5 on 2021-01-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertasksapi', '0003_auto_20210120_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Descrição',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Estado',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
